#!/bin/bash
## test-http-stat
## - provides stats for urls in clipboard
## version 0.0.1 - initial
##################################################
sanitize() {
  echo ${@} \
  | sed -e 's/[^a-z0-9:/.]//g'
}
stat-url() { { local url ; url="$( sanitize ${1} )" ; }
  echo "\"${url}\""
  curl --url "${url}" -I --silent
}
stat-urls() {
  local url
  for url in $( cat /dev/clipboard )
  do
    stat-url ${url} 
  done
}
test-http-stat() {
  stat-urls 
  stat-urls | grep 404
  stat-urls | grep 404 | wc -l
}
##################################################
if [ ${#} -eq 0 ] 
then
 true
else
 exit 1 # wrong args
fi
##################################################
test-http-stat
##################################################
## generated by create-stub2.sh v0.1.1
## on Wed, 09 Jan 2019 10:03:48 +0900
## see <https://github.com/temptemp3/sh2>
##################################################
